// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3I3w4GYcjCAbKp-HvcMRuqvEyclQyIlU',
    appId: '1:685166268939:web:2994680fa5fc5fdf58ed0e',
    messagingSenderId: '685166268939',
    projectId: 'noteworthy-za',
    authDomain: 'noteworthy-za.firebaseapp.com',
    storageBucket: 'noteworthy-za.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCrK4ByroljZvFA_zpiyPtB_-OVCMcuM',
    appId: '1:685166268939:android:48737b091c39650c58ed0e',
    messagingSenderId: '685166268939',
    projectId: 'noteworthy-za',
    storageBucket: 'noteworthy-za.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZugiYvTYCVBzn-v2ES9Rn5XIx4Q8jF1g',
    appId: '1:685166268939:ios:54e9ff5866bb8d3758ed0e',
    messagingSenderId: '685166268939',
    projectId: 'noteworthy-za',
    storageBucket: 'noteworthy-za.firebasestorage.app',
    iosBundleId: 'com.macmillan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZugiYvTYCVBzn-v2ES9Rn5XIx4Q8jF1g',
    appId: '1:685166268939:ios:54e9ff5866bb8d3758ed0e',
    messagingSenderId: '685166268939',
    projectId: 'noteworthy-za',
    storageBucket: 'noteworthy-za.firebasestorage.app',
    iosBundleId: 'com.macmillan.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3I3w4GYcjCAbKp-HvcMRuqvEyclQyIlU',
    appId: '1:685166268939:web:f7bb0c4a4d13b5d658ed0e',
    messagingSenderId: '685166268939',
    projectId: 'noteworthy-za',
    authDomain: 'noteworthy-za.firebaseapp.com',
    storageBucket: 'noteworthy-za.firebasestorage.app',
  );
}
